### ISSUE TITLE
Error: External Program Lookup Failed

### ISSUE THREAD

**Issue by Sivan-del** [claranet/terraform-azurerm-run-iaas#1]
![Error_Capture](https://user-images.githubusercontent.com/67947223/167595716-6be60260-9dd7-4d4a-b906-9c720e9d1240.PNG)
Having this Error when trying to do a terraform destroy, do you know why this happens & how to fix it?

**Comment by rossifumax** [comment]
**Hello**,

In our module, we are executing bash scripts.

According to your screenshot, you're executing our module on a Windows platform, but the module try to find and execute the `bash` binary which is, appartently, not available on your machine.

It's most a problem from  your machine than our module.

Hope it helps you to debug this problem.

Regards

**Comment by Sivan-del** [comment]
> 

are you referring to the machine that I am running your module from or the VM that Update Management runs on?

**Comment by rossifumax** [comment]
Yes, the machine that's running the module.

But you've opened an issue on the `run-iaas` module but according to your screenshot you have the problem with the submodule `logs` from our [run-common module](https://github.com/claranet/terraform-azurerm-run-common/tree/master/).
