### ISSUE TITLE
Error: Can not parse "workspace_id" as a resource id: Cannot parse Azure ID: parse "": empty url

### ISSUE THREAD

**Issue by Sivan-del** [claranet/terraform-azurerm-run-iaas#2]
![image](https://user-images.githubusercontent.com/67947223/167878679-914f1083-973b-4f0e-8140-c13bf7abd529.png)

Hey,
getting this error when running "terraform plan" from "terraform-azurerm-run-iaas/examples/update-managemant"
could you please assist?

**Comment by BzSpi** [comment]
Hello @Sivan-del 

As the error mention, you're setting an empty value as parameter instead of a real Log Analytics Workspace ID.
